spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: http://192.168.1.13/yangtao/config.git
          username: yangtao
          password: Xp001005
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
server:
  port: 9091