#  http://localhost:9090/erueka/
spring:
  application:
    name: eureka
server:
  port: 9090
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
